pizza/config/urls.py
from django.contrib import admin
from django.urls import path, include

from features.views import index
import debug_toolbar

from order.views import create_order, create_model_order
from pizza.views import pizza_detail_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('order/create_order/', create_order, name='create_order'),
    path('createmodelorder', create_model_order, name='createmodelorder'),
    path('<slug:slug>', pizza_detail_view, name='pizza_detail'),
    path('__debug__/', include(debug_toolbar.urls)),

]

pizza/features/models.py
from django.db import models

# Create your models here.

pizza/order/models.py
from django.db import models
from pizza.models import PizzaModel
from django.utils.translation import gettext_lazy as _
# Create your models here.


class OrderModel(models.Model):
    class DeliveryStatus(models.TextChoices):
        PENDING = 'PEN', _('Pending')
        DELIVERED = 'DEL', _('Delivered')

    address = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    pizza_order = models.ManyToManyField(PizzaModel)
    delivery_status = models.CharField(
        max_length=3,
        choices=DeliveryStatus.choices,
        default=DeliveryStatus.PENDING
    )

    class Meta:
        verbose_name = 'Orders'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return f'Address: {self.address}; Order: {", ".join([pizza.name for pizza in self.pizza_order.all()])}'

    def all_orders(self):
        return '\n'.join([pizza.name for pizza in self.pizza_order.all()])


# class OrderProxy(OrderModel.pizza_order.through):
#     class Meta:
#         proxy = True

#     def __str__(self):
#         return str(self.ordermodel)

pizza/pizza/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.
def slugify_(stroke):
    new = ''
    for i in stroke:
        if i == ' ':
            new += '-'
        elif i.isalnum():
            new += i.lower()

    return new

class ToppingsModel(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Toppings'
        verbose_name_plural = 'Toppings'
        
    def __str__(self):
        return self.name

class PizzaModel(models.Model):
    name = models.CharField(max_length=50)
    name_slug = models.SlugField(blank=True, null=True)
    toppings = models.ManyToManyField(ToppingsModel, verbose_name='toppings')

    class Meta:
        verbose_name = 'My pizza recipes'
        verbose_name_plural = 'Pizza recipes'

    def __str__(self):
        return f"{self.name} : {', '.join([topping.name for topping in self.toppings.all()])}"
    
    def all_toppings(self):
        return "\n".join([t.name for t in self.toppings.all()])

    def get_absolute_url(self):
        return reverse('pizza_detail', kwargs={'slug': self.name_slug})

    def save(self, *args, **kwargs):
        if not self.name_slug:
            self.name_slug = slugify_(self.name)
        return super().save(*args, **kwargs)

# class PizzaProxy(PizzaModel.toppings.through):
#     class Meta:
#         proxy = True

#     def __str__(self):
#         return ''

pizza/order/forms.py
from django import forms
from pizza.models import PizzaModel
from .models import OrderModel

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Button, ButtonHolder, Field
PIZZAS = [
    (f'{p.id}', f'{p.name}') for p in PizzaModel.objects.all()
]

DEL_STATUS = [('PEN', 'Pending'), ('DEL', 'Delivered')]


class CreateForm(forms.Form):
    address = forms.CharField(required=True)
    choice = forms.ChoiceField(
        choices=PIZZAS,
        help_text='If you want some extra. Send us <a href="#">Message</a>',
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'pizzas'}))
    delivery_status = forms.ChoiceField(
        choices=DEL_STATUS
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('address'),
            Field('choice'),
            Field('delivery_status'),
            ButtonHolder(Submit('order', 'Order', css_class='btn btn-danger'))
        )


class CreateOrderModelForm(forms.ModelForm):
    error_css_class = 'error-field-class'
    required_css_class = 'required-field-class'

    class Meta:
        model = OrderModel
        fields = ['address', 'pizza_order']
        widgets = {
            'address': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your address:'
            }),
            'pizza_order': forms.CheckboxSelectMultiple()
        }

pizza/features/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    data = [i for i in range(10)]
    return render(request, 'index.html', {'test_data': data})

pizza/order/views.py
from django.shortcuts import redirect, render

from pizza.models import PizzaModel
from .models import OrderModel
from .forms import CreateForm, CreateOrderModelForm
from django.forms import modelformset_factory
# Create your views here.

def create_order(request, *args, **kwargs):
    pizzas = PizzaModel.objects.all()
    order_form = CreateForm(request.POST or None)
    if order_form.is_valid():
        address = order_form.cleaned_data.get('address')
        order = dict(order_form.data).get('choice')
        pizza_objects = [PizzaModel.objects.get(id=i) for i in order]
        new_order = OrderModel.objects.create(address=address)
        new_order.pizza_order.add(*pizza_objects)
        new_order.save()
        return redirect('create_order')

    context = {
        'pizza': pizzas,
        'order_form': order_form
    }
    return render(request, 'order/create_order.html', context=context)

def create_model_order(request, *args, **kwargs):
    pizzas = PizzaModel.objects.all()
    model_form = CreateOrderModelForm(request.POST or None)
    # OrderFormSet = modelformset_factory(
    #     OrderModel,
    #     form=CreateOrderModelForm,
    #     extra=2,
    # )
    # model_form = OrderFormSet(
    #     request.POST or None,
    #     queryset=OrderModel.objects.none(),
    #     initial=[{
    #         'address': 'modelformset street'
    #     }]
    # )
    # if model_form.is_valid():
    #     model_form.save()
    #     return redirect('createmodelorder')

    context = {
        'pizza': pizzas,
        'modelform': model_form,
    }
    return render(request, 'order/create_model_order.html', context=context)

def create_model_form(request, *args, **kwargs):
    pizzas = PizzaModel.objects.all()
    # order_list = OrderModel.objects.all()
    OrderFormSet = modelformset_factory(
        OrderModel,
        form=CreateOrderModelForm,
        extra=2,
    )
    model_form = OrderFormSet(
        request.POST or None,
        queryset=OrderModel.objects.none(),
        initial=[{
            'address': 'modelformset street'
        }]
    )
    if model_form.is_valid():
        model_form.save()
        return redirect('createmodelorder')

pizza/pizza/views.py
from django.shortcuts import render
from .models import PizzaModel
# Create your views here.

def pizza_detail_view(request, *args, **kwargs):
    print(kwargs)
    pizza_object = PizzaModel.objects.get(name_slug=kwargs.get('slug'))
    context = {'pizza_objects': pizza_object}
    return render(request, 'pizza/pizza_detail.html', context)

pizza/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    {% for data in test_data %}
        <ul>
            <li>{{ data }}</li>
        </ul>
    {% endfor %}
</body>
</html>

pizza/templates/order/create_model_order.html
<h1>Our pizzas! Tasty and delicious</h1>
<ul>
    {% for i in pizza %}
        <li>{{i.name}}</li>
        <div>
            <mark>Ingridiento</mark>
        </div>
        <ul>
            {% for j in i.toppings.all %}
                <li>{{ j.name }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>

<form action="" method="post" class="form">
    {% csrf_token %}
    {{ modelform.as_p }}

    <input type="submit" value="place order" class="order">
</form>

<button class="more">add more pizzas</button>

<script>
    let pizza = document.querySelector('#id_pizza_order')
    let order = document.querySelector('.order')
    let more = document.querySelector('.more')
    let form = document.querySelector('.form')

    more.addEventListener('click', (e) => {
        e.preventDefault()
        p = document.createElement('p')
        l = document.createElement('label')
        l.setAttribute('for', 'id_pizza_order')
        l.textContent = 'Pizza order:'
        cloned = pizza.cloneNode(true)
        p.append(l)
        p.append(cloned)
        form.insertBefore(p, order)
    })
</script>

pizza/templates/order/create_order.html
{% load crispy_forms_tags %}
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<h1>Our pizzas! Tasty and delicious</h1>
{% crispy order_form %}
<ul>
    {% for i in pizza %}
        <li>
            <a href="{{ p.name_slug }}">{{p.name}}</a>
        </li>
        <div>
            <mark>Ingridiento</mark>
        </div>
        <ul>
            {% for j in i.toppings.all %}
                <li>{{ j.name }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
</ul>
<!-- <form action="" method="post" class="form"> -->
    <!-- {% csrf_token %}
    {{ order_form|crispy }}
    <input type="submit" class="btn btn-danger" value="Order">
</form> -->
<!-- <button class="more">add more pizza</button> -->

<!-- <script>
    let pizza = document.querySelector('.pizzas')
    let order = document.querySelector('.order')
    let more = document.querySelector('.more')
    let form = document.querySelector('.form')

    more.addEventListener('click', (e) => {
        e.preventDefault()
        p = document.createElement('p')
        l = document.createElement('label')
        l.setAttribute('for', 'id_choice')
        l.textContent = 'Choice:'
        cloned = pizza.cloneNode(true)
        p.append(l)
        p.append(cloned)
        form.insertBefore(p, order)
    })
</script> -->

pizza/templates/pizza/pizza_detail.html
<h1>Pizza name</h1>
{{pizza_object.name}}
<h1>Pizza ingridients</h1>